from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.alert import Alert

browser = webdriver.Firefox(executable_path = "C:\geckodriver-v0.30.0-win64\geckodriver")
browser.get('http://automationpractice.com/index.php')
browser.find_element_by_class_name("login").send_keys(Keys.ENTER)
time.sleep(5)
browser.find_element_by_id("email_create").send_keys("usha999@gmail.com")
browser.find_element_by_name("SubmitCreate").send_keys(Keys.ENTER)
time.sleep(5)
female_radio_button=browser.find_element_by_xpath('/html/body/div/div[2]/div/div[3]/div/div/form/div[1]/div[1]/div[2]/label')
browser.find_element_by_id("uniform-id_gender2")
female_radio_button.click()
time.sleep(5)

browser.find_element_by_id("customer_firstname").send_keys("Usha1234")
time.sleep(5)
browser.find_element_by_id("customer_lastname").send_keys("87")
time.sleep(5)
browser.find_element_by_id("passwd").send_keys("Usha@123")
time.sleep(5)
dropdown_element=browser.find_element_by_xpath("//*[@id='days']")
dropdown_object = Select(dropdown_element)
dropdown_object.select_by_value("13")
time.sleep(5)
dropdown_element=browser.find_element_by_xpath('/html/body/div/div[2]/div/div[3]/div/div/form/div[1]/div[6]/div/div[2]/div/select')
dropdown_object = Select(dropdown_element)
dropdown_object.select_by_value("6")
time.sleep(5)
dropdown_element=browser.find_element_by_xpath('/html/body/div/div[2]/div/div[3]/div/div/form/div[1]/div[6]/div/div[3]/div/select')
dropdown_object = Select(dropdown_element)
dropdown_object.select_by_value("1999")
time.sleep(5)
browser.find_element_by_id("address1").send_keys("PWD quarters")
time.sleep(5)
browser.find_element_by_id("city").send_keys("Hassan")
time.sleep(5)
dropdown_element=browser.find_element_by_xpath('//*[@id="id_state"]')
dropdown_object = Select(dropdown_element)
dropdown_object.select_by_value("17")
time.sleep(5)
browser.find_element_by_id("postcode").send_keys("WXYZ")
time.sleep(5)
dropdown_element=browser.find_element_by_xpath('//*[@id="id_country"]')
dropdown_object = Select(dropdown_element)
dropdown_object.select_by_value("21")
time.sleep(5)
browser.find_element_by_id("phone_mobile").send_keys("ABCDEFGH")
time.sleep(5)
browser.find_element_by_id("alias").send_keys("belur")
time.sleep(5)
browser.find_element_by_name("submitAccount").send_keys(Keys.ENTER)
time.sleep(5)